# Gradle Properties
org.gradle.jvmargs = -Xmx2G
org.gradle.parallel = true

# Fabric Properties
minecraft_version = 26.2
loader_version = 0.19.3

# Mod Properties
mod_version = 1.0.0
maven_group = com.yaligaming
archives_base_name = HebrewFix

# Fabric API
fabric_version = 0.152.2+26.2

# Mod Menu
modmenu_version = 20.0.1
